title: My Enki Blog
url:   http://enkiblog.com
author: 
  name:    Don Alias
  email:   don@enkiblog.com
  open_id: http://enkiblog.com

open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://username.myopenid.com
