title: My Enki Blog
url:   http://enkiblog.com
exception_notifications: don@enkiblog.com

# Delete the following section if your site will not be acting as an OpenID delegate
open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://username.myopenid.com
