title: Roboblog
url:   http://roboblog.com
author: 
  name:    Don Alias
  email:   don@roboblog.com
  open_id: http://roboblog.com

open_id_delegation:
  server:   http://www.myopenid.com/server
  delegate: http://username.myopenid.com
